### ISSUE TITLE
Self signed certificates 

### ISSUE THREAD

**Issue by owaku** [kruzhkov/traccar-manager-ios#1]
Hello, i've got a server running traccar server with self signed certificates. When i try to connect using your app it blocks and appears a window "couldn't login...." 
I've got My keys installed in iOS.
Is there any  possibility to use self signed certs?

Thank you in advance
![img_0201](https://user-images.githubusercontent.com/31340372/29729011-b4b8facc-89da-11e7-9319-792f830a1dee.JPG)

**Comment by kruzhkov** [comment]
Hello, a new version of the app allows self signed certificates, update of app store

**Comment by owaku** [comment]
Ok. Thank you
You do a great job!! 

Diego Isasi
@gotxe
