### ISSUE TITLE
Summary report sources

### ISSUE THREAD

**Issue by fheisenberg** [kruzhkov/traccar-manager-ios#3]
Hello dear,
i updated the app from Apple Store a few days ago and works fine!, Thank you. My question is about the source update because the current source code does not match with the app version in the Apple Store, do you have in mind update also this source code?

Thanks in advance

**Comment by kruzhkov** [comment]
Пан
12 окт. 2017 г. 18:16 пользователь "fheisenberg" <notifications@github.com>
написал:

**Comment by kruzhkov** [comment]
Hello
I updated source code
