### ISSUE TITLE
Error New Events Report (String could not be serialized with encoding: Uniode (UTF-8))

### ISSUE THREAD

**Issue by ubarni** [kruzhkov/traccar-manager-ios#4]
Hi,

i tried the new events report in Traccar Manager+ and get the error "String could not be serialized with encoding: Uniode (UTF-8)!
the existing summary report works fine?

I am using latest traccar server installed on a raspberry pi connected to a mySQL database on my Synology NAS.

Barni

**Comment by kruzhkov** [comment]
Hi Barni,

Screenshot please

**Comment by ubarni** [comment]
![image](https://user-images.githubusercontent.com/5228490/32573909-ecbcec0a-c4cf-11e7-91b8-6e2704cbb841.png)

**Comment by kruzhkov** [comment]
"Summary" report works?

**Comment by ubarni** [comment]
Yes. Summary report is fine... Checked it again right now...

**Comment by kruzhkov** [comment]
try in the browser

http://localhost/api/reports/events?deviceId=ID&from=2017-11-01T00:00:00.000Z&to=2017-11-09T23:59:59.000Z

where localhost - your traccar server, ID - device id 

what answer?

**Comment by ubarni** [comment]
Seems to work...
![image](https://user-images.githubusercontent.com/5228490/32575178-9a643f9a-c4d3-11e7-95fa-c5f2fc8c423d.png)

**Comment by ubarni** [comment]
[report.xlsx](https://github.com/kruzhkov/traccar-manager-ios/files/1455465/report.xlsx)

**Comment by ubarni** [comment]
Here is the API result of the summary report.
It is a json array instead of an xlsx file!
[{"deviceId":3,"deviceName":"Skoda Yeti","distance":663284.39,"averageSpeed":18.151805197845995,"maxSpeed":94.83,"spentFuel":0.0,"engineHours":0}]

**Comment by kruzhkov** [comment]
Please json array events from 2017-11-01 to 2017-11-08

**Comment by ubarni** [comment]
If i ran the .../api/reports/events... i get an excel file to download as shown above.
How do i get the JSON-Array?

**Comment by kruzhkov** [comment]
You can use the program  https://www.getpostman.com

![2017-11-09 23 22 01](https://user-images.githubusercontent.com/30497843/32627852-f1eca55a-c5a4-11e7-87c8-689cf2e32a40.png)

**Comment by ubarni** [comment]
[events.json.txt](https://github.com/kruzhkov/traccar-manager-ios/files/1459396/events.json.txt)

**Comment by kruzhkov** [comment]
Hi Uwe,
Test in new version 1.5

What's new
- Animation devices move
- Switch my location
- Add report events attributes
- Show events on map
- Fix request json

**Comment by ubarni** [comment]
I will test it and give you feedback.
Thank you so much.

**Comment by ubarni** [comment]
Hi Sergey,

- Switch my location works fine now
- Event report also works now (No UTF8 Error)
- I can show the events also on the map. Great
- The animation devices moves (i am not sure what it does) i will check while driving home and expect a trace on the map?.

Good Job. Thank you...
Barni

**Comment by kruzhkov** [comment]
Thank you
