### ISSUE TITLE
App crashs right after login.

### ISSUE THREAD

**Issue by ubarni** [kruzhkov/traccar-manager-ios#6]
Since a view days the App crashs right after pressing login on my iPhone SE iOS 11.2.1
Reinstalled, but same issue. Now i can see for a few milliseconds the question to use GPS.

**Comment by ubarni** [comment]
After rebooting my iPhone (not only turning off and on) it works again!

**Comment by CoolFX2011** [comment]
It’s happening to me also. Even after a reboot on my iPhone 11 Pro with IOS 13.1.3.
It was working ok, but now it’s happening. Works perfectly on official app.
Too bad. Traccar Manager+ have a much nicer interface.
