### ISSUE TITLE
Access problem

### ISSUE THREAD

**Issue by igor98800** [kruzhkov/traccar-manager-ios#8]
Hello Sergey,

ios 11.3
Traccar manager+  v1.5

Unable to access my own server through ios 
my traccar url address server is like    my.traccarserver.tv:8082    
perhaps Traccar Manager+ doesn't support the port?
![photo5001252304388728824](https://user-images.githubusercontent.com/37465908/37552977-1d529a42-2a13-11e8-966c-c3098f760f89.jpg)
Can you help please ?
Regards.
Igor

**Comment by kruzhkov** [comment]
Hi,
Try post request 
http://my.traccarserver.tv:8082/api/session

what answer?

**Comment by igor98800** [comment]
Hello, don't work so much....

![photo5587269887206729644](https://user-images.githubusercontent.com/37465908/37693369-548bfc30-2d13-11e8-996d-3a5a8a0b2765.jpg)

May you try be yourself, I'll give you an access, please give me your private mail.

Thanks.
igor

**Comment by kruzhkov** [comment]
Ok, mail sergey@dyrex.net

**Comment by kruzhkov** [comment]
You have an unofficial version of Traccar Server.
